name = "twitter-clone-worker"
main = "src/index.ts"
compatibility_date = "2024-02-01"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
  queue = "tweet-queue"
  binding = "TWEET_QUEUE"

[[queues.consumers]]
  queue = "tweet-queue"
  max_batch_size = 10
  max_batch_timeout = 30
  max_retries = 3

[vars]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
JWT_SECRET = ""

# Development environment
[env.dev]
vars = { ENVIRONMENT = "dev" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }
